[package]
name = "cargo-generate"
description = "cargo, make me a project"
version = "0.5.1"
authors = [
    "Ashley Williams <ashley666ashley@gmail.com>"
]
license = "MIT/Apache-2.0"
repository = "https://github.com/ashleygwilliams/cargo-generate"
readme = "README.md"
edition = "2018"

[dependencies]
cargo = "0.49.0"
console = "0.14.0"
dialoguer = "0.7.1"
indicatif = "0.15.0"
git2 = "0.13.14"
tempfile = "3.1"
regex = "1.4"
heck = "0.3.2"
liquid = "0.21"
liquid-core = "0.21"
liquid-lib = "0.21"
liquid-derive = "0.21"
walkdir = "2.3"
remove_dir_all = "0.6.1"
ignore = "0.4.17"
openssl = { version = "0.10.32", optional = true }
url = "2.2"
structopt = "0.3.21"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"

[dev-dependencies]
predicates = "1.0"
assert_cmd = "1.0"

[features]
vendored-openssl = ['openssl/vendored']

[[bin]]
path = "src/main.rs"
name = "cargo-generate"
